# Local development overrides

image:
  registry: registry-1.docker.io
  repository: harness/mcp-server
  pullPolicy: IfNotPresent
  tag: "1.0.0-beta.16"
  digest: ""
  imagePullSecrets: []

# Override global settings
global:
  autoscaling:
    enabled: false
autoscaling:
  enabled: false

# Run only 1 replica for local development
replicaCount: 1

# Use NodePort for easy local access
service:
  type: NodePort
  port: 8080
  nodePort: 30080

localMode: True

pdb:
  create: false

# Local environment configuration
configLocal:
  HARNESS_BASE_URL: "https://app.harness.io"
secrets:
  default:
    HARNESS_API_KEY: "<PAT>" # or <SAT>                                                              
