apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-server-external.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp-server-external.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.service.annotations .Values.global.commonAnnotations }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: mcp
      port: {{.Values.service.port}}
      protocol: TCP
      targetPort: {{.Values.service.port}}
  selector:
    {{- include "mcp-server-external.selectorLabels" . | nindent 4 }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- if and (eq .Values.service.sessionAffinity "ClientIP") .Values.service.sessionAffinityTimeout }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.service.sessionAffinityTimeout }}
  {{- end }}